version: '3.4'

services:
  auctionhousemongodb:
    image: mongo

  rabbitmq:
    image: rabbitmq:3-management

  actionhousesqldb:
    image: mcr.microsoft.com/mssql/server

  auctionhouse.products:
    image: ${DOCKER_REGISTRY-}auctionhouseproducts
    build:
      context: .
      dockerfile: AuctionHouse.Products/Dockerfile

  auctionhouse.sourcing:
    image: ${DOCKER_REGISTRY-}auctionhousesourcing
    build:
      context: .
      dockerfile: AuctionHouse.Sourcing/Dockerfile

  auctionhouse.order:
    image: ${DOCKER_REGISTRY-}auctionhouseorder
    build:
      context: .
      dockerfile: AuctionHouse.Order/Dockerfile

  auctionhouse.apigateway:
    image: ${DOCKER_REGISTRY-}auctionhouseapigateway
    build:
      context: .
      dockerfile: AuctionHouse.APIGateway/Dockerfile

