version: '3.4'

services:
  auctionhousemongodb:
    image: mongo

  rabbitmq:
    image: rabbitmq:3-management

  sourcingsqldb:
    image: mcr.microsoft.com/mssql/server

  auctionhouse.products:
    image: ${DOCKER_REGISTRY-}auctionhouseproducts
    build:
      context: .
      dockerfile: AuctionHouse.Products/Dockerfile

  auctionhouse.sourcing:
    image: ${DOCKER_REGISTRY-}auctionhousesourcing
    build:
      context: .
      dockerfile: AuctionHouse.Sourcing/Dockerfile

