version: '3.4'

services:
  auctionhousemongodb:
    container_name: auctionhousemongodb
    restart: always
    volumes:
       - ${WEBAPP_STORAGE_HOME}/site:/data/db
    ports:
       - "27017:27017" 

  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
       - "5672:5672"
       - "15672:15672"

  auctionhouse.products:
    container_name: auctionhouseproducts
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ProductDatabaseSettings:ConnectionStrings=mongodb://auctionhousemongodb:27017"
    depends_on:
      - auctionhousemongodb
    ports:
      - "8000:80"
    volumes:
      - ${HOME}/Microsoft/UserSecrets:/root/.microsoft/usersecrets
      - ${HOME}/ASP.NET/Http:/root/.aspnet/http/

  auctionhouse.sourcing:
    container_name: auctionhousesourcing
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "SourcingDatabaseSettings:ConnectionString=mongodb://auctionhousemongodb:27017"
      - "EventBus:HostName=rabbitmq"
    depends_on:
      - auctionhousemongodb
      - rabbitmq
    volumes:
      - ${HOME}/Microsoft/UserSecrets:/root/.microsoft/usersecrets
      - ${HOME}/ASP.NET/Http:/root/.aspnet/http/
    ports:
      - "8001:80"

